"""
EXODUS-SPECULUM - Configuration du Sanctum
"""

from .paths import (
    ROOT_DRIVE,
    SHARED_RESOURCES,
    AI_MODELS_DIR,
    FRIGATES,
    F00_CODEBASE, F00_INPUT, F00_OUTPUT,
    F01_CODEBASE, F01_INPUT, F01_OUTPUT,
    F02_CODEBASE, F02_INPUT, F02_OUTPUT,
    F03_CODEBASE, F03_INPUT, F03_OUTPUT,
    F04_CODEBASE, F04_INPUT, F04_OUTPUT,
    F05_CODEBASE, F05_INPUT, F05_OUTPUT,
    F06_CODEBASE, F06_INPUT, F06_OUTPUT,
    F07_CODEBASE, F07_INPUT, F07_OUTPUT,
    DEPTH_MODEL_PATH,
    DEPTH_MODEL_BASE_PATH,
)

__all__ = [
    'ROOT_DRIVE',
    'SHARED_RESOURCES',
    'AI_MODELS_DIR',
    'FRIGATES',
    'F00_CODEBASE', 'F00_INPUT', 'F00_OUTPUT',
    'F01_CODEBASE', 'F01_INPUT', 'F01_OUTPUT',
    'F02_CODEBASE', 'F02_INPUT', 'F02_OUTPUT',
    'F03_CODEBASE', 'F03_INPUT', 'F03_OUTPUT',
    'F04_CODEBASE', 'F04_INPUT', 'F04_OUTPUT',
    'F05_CODEBASE', 'F05_INPUT', 'F05_OUTPUT',
    'F06_CODEBASE', 'F06_INPUT', 'F06_OUTPUT',
    'F07_CODEBASE', 'F07_INPUT', 'F07_OUTPUT',
    'DEPTH_MODEL_PATH',
    'DEPTH_MODEL_BASE_PATH',
]
