"""
EXODUS-SPECULUM - Configuration des Chemins du Sanctum
ÉDIT IMPÉRIAL - Ne pas modifier sans autorisation du Sigillite
"""

ROOT_DRIVE = "/content/drive/MyDrive/EXODUS-SPECULUM/"
SHARED_RESOURCES = "/content/drive/MyDrive/EXODUS_SHARED_RESOURCES/"
AI_MODELS_DIR = SHARED_RESOURCES + "AI_MODELS/"

FRIGATES = {
    "F00_CORTEX": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_00_CORTEX/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_00_CORTEX/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_00_CORTEX/OUTPUT/",
    },
    "F01_SCANNER": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_01_SCANNER/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_01_SCANNER/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_01_SCANNER/OUTPUT/",
    },
    "F02_SCENOGRAPHE": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_02_SCENOGRAPHE/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_02_SCENOGRAPHE/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_02_SCENOGRAPHE/OUTPUT/",
    },
    "F03_PROJECTIONNISTE": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_03_PROJECTIONNISTE/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_03_PROJECTIONNISTE/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_03_PROJECTIONNISTE/OUTPUT/",
    },
    "F04_LOGISTIQUE": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_04_LOGISTIQUE/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_04_LOGISTIQUE/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_04_LOGISTIQUE/OUTPUT/",
    },
    "F05_DIRECTEUR_PHOTO": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_05_DIRECTEUR_PHOTO/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_05_DIRECTEUR_PHOTO/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_05_DIRECTEUR_PHOTO/OUTPUT/",
    },
    "F06_ALCHIMISTE": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_06_ALCHIMISTE/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_06_ALCHIMISTE/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_06_ALCHIMISTE/OUTPUT/",
    },
    "F07_PORTE_AVIONS": {
        "CODEBASE": ROOT_DRIVE + "FRIGATE_07_PORTE_AVIONS/CODEBASE/",
        "INPUT": ROOT_DRIVE + "FRIGATE_07_PORTE_AVIONS/INPUT/",
        "OUTPUT": ROOT_DRIVE + "FRIGATE_07_PORTE_AVIONS/OUTPUT/",
    },
}

F00_CODEBASE = FRIGATES["F00_CORTEX"]["CODEBASE"]
F00_INPUT = FRIGATES["F00_CORTEX"]["INPUT"]
F00_OUTPUT = FRIGATES["F00_CORTEX"]["OUTPUT"]

F01_CODEBASE = FRIGATES["F01_SCANNER"]["CODEBASE"]
F01_INPUT = FRIGATES["F01_SCANNER"]["INPUT"]
F01_OUTPUT = FRIGATES["F01_SCANNER"]["OUTPUT"]

F02_CODEBASE = FRIGATES["F02_SCENOGRAPHE"]["CODEBASE"]
F02_INPUT = FRIGATES["F02_SCENOGRAPHE"]["INPUT"]
F02_OUTPUT = FRIGATES["F02_SCENOGRAPHE"]["OUTPUT"]

F03_CODEBASE = FRIGATES["F03_PROJECTIONNISTE"]["CODEBASE"]
F03_INPUT = FRIGATES["F03_PROJECTIONNISTE"]["INPUT"]
F03_OUTPUT = FRIGATES["F03_PROJECTIONNISTE"]["OUTPUT"]

F04_CODEBASE = FRIGATES["F04_LOGISTIQUE"]["CODEBASE"]
F04_INPUT = FRIGATES["F04_LOGISTIQUE"]["INPUT"]
F04_OUTPUT = FRIGATES["F04_LOGISTIQUE"]["OUTPUT"]

F05_CODEBASE = FRIGATES["F05_DIRECTEUR_PHOTO"]["CODEBASE"]
F05_INPUT = FRIGATES["F05_DIRECTEUR_PHOTO"]["INPUT"]
F05_OUTPUT = FRIGATES["F05_DIRECTEUR_PHOTO"]["OUTPUT"]

F06_CODEBASE = FRIGATES["F06_ALCHIMISTE"]["CODEBASE"]
F06_INPUT = FRIGATES["F06_ALCHIMISTE"]["INPUT"]
F06_OUTPUT = FRIGATES["F06_ALCHIMISTE"]["OUTPUT"]

F07_CODEBASE = FRIGATES["F07_PORTE_AVIONS"]["CODEBASE"]
F07_INPUT = FRIGATES["F07_PORTE_AVIONS"]["INPUT"]
F07_OUTPUT = FRIGATES["F07_PORTE_AVIONS"]["OUTPUT"]

DEPTH_MODEL_PATH = AI_MODELS_DIR + "depth_anything_v2/depth_anything_v2_vitl.pth"
DEPTH_MODEL_BASE_PATH = AI_MODELS_DIR + "depth_anything_v2/depth_anything_v2_vitb.pth"
