#!/usr/bin/env python3
"""
EXODUS-SPECULUM - Frégate PORTE-AVIONS - Metadata Injector
Anti-shadowban via métadonnées uniques et variations anti-fingerprint.

Ce module applique la Loi VI - Invisibilité du CODEX SPECULUM:
- Métadonnées uniques pour chaque export
- Micro-variations imperceptibles pour éviter le fingerprinting
- Timestamps dynamiques
- IDs uniques par vidéo

Philosophie: L'Invisibilité
Les plateformes détectent le contenu dupliqué via fingerprinting audio/vidéo.
Ces variations subtiles rendent chaque export unique sans altérer la qualité perçue.

Usage:
    injector = MetadataInjector()
    
    output = injector.inject_unique_metadata(
        video_path="/path/to/video.mp4",
        output_path="/path/to/output.mp4",
        title="SPECULUM Tour - Villa Monaco"
    )
    
    output = injector.apply_anti_fingerprint(
        video_path="/path/to/video.mp4",
        output_path="/path/to/output_unique.mp4",
        intensity="subtle"
    )
"""

import subprocess
import random
import uuid
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

EXODUS_VERSION = "0.8.0"

ANTI_FINGERPRINT_PARAMS = {
    "subtle": {
        "color": 0.01,
        "noise": 1,
        "speed": 0.001,
        "crop": 1
    },
    "moderate": {
        "color": 0.02,
        "noise": 2,
        "speed": 0.002,
        "crop": 2
    },
    "aggressive": {
        "color": 0.03,
        "noise": 3,
        "speed": 0.003,
        "crop": 3
    }
}


class MetadataInjector:
    """
    Injecte des métadonnées et variations pour éviter la détection
    de contenu dupliqué par les plateformes (Loi VI - Invisibilité).
    
    Stratégies:
    1. Métadonnées uniques (titre, timestamp, encoder ID)
    2. Micro color shift (invisible à l'œil)
    3. Subtle noise injection
    4. Tiny speed variation (±0.1-0.3%)
    5. Random crop (1-3 pixels)
    
    Usage:
        injector = MetadataInjector()
        
        output = injector.inject_unique_metadata(video_path, output_path)
        output = injector.apply_anti_fingerprint(video_path, output_path, "subtle")
    """
    
    def __init__(self, verbose: bool = True):
        """
        Args:
            verbose: Affiche les logs détaillés
        """
        self.verbose = verbose
        
    def _log(self, message: str) -> None:
        """Log conditionnel."""
        if self.verbose:
            print(message)
    
    def check_ffmpeg(self) -> bool:
        """Vérifie que FFmpeg est installé."""
        return shutil.which("ffmpeg") is not None
    
    def inject_unique_metadata(
        self,
        video_path: str,
        output_path: str,
        title: Optional[str] = None,
        description: Optional[str] = None,
        artist: Optional[str] = None,
        copyright_text: Optional[str] = None
    ) -> str:
        """
        Ajoute des métadonnées uniques via FFmpeg.
        
        Args:
            video_path: Vidéo source
            output_path: Chemin de sortie
            title: Titre personnalisé (défaut: auto-généré)
            description: Description
            artist: Artiste/créateur
            copyright_text: Copyright
            
        Returns:
            Chemin de la vidéo avec métadonnées
        """
        self._log(f"   📋 Injection métadonnées: {video_path}")
        
        creation_time = datetime.now().isoformat()
        unique_id = str(uuid.uuid4())[:8]
        
        if title is None:
            title = f"SPECULUM_TOUR_{unique_id}"
        
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        cmd = [
            "ffmpeg", "-y",
            "-i", video_path,
            "-metadata", f"title={title}",
            "-metadata", f"creation_time={creation_time}",
            "-metadata", f"encoder=EXODUS-SPECULUM-v{EXODUS_VERSION}-{unique_id}",
            "-metadata", f"comment=Generated by EXODUS-SPECULUM Pipeline"
        ]
        
        if description:
            cmd.extend(["-metadata", f"description={description}"])
        
        if artist:
            cmd.extend(["-metadata", f"artist={artist}"])
        
        if copyright_text:
            cmd.extend(["-metadata", f"copyright={copyright_text}"])
        
        cmd.extend(["-c", "copy", output_path])
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            self._log(f"   ❌ Erreur: {result.stderr}")
            raise RuntimeError(f"FFmpeg metadata injection failed: {result.stderr}")
        
        self._log(f"   ✓ Métadonnées injectées: {title}")
        self._log(f"   ✓ ID unique: {unique_id}")
        
        return output_path
    
    def apply_anti_fingerprint(
        self,
        video_path: str,
        output_path: str,
        intensity: str = "subtle"
    ) -> str:
        """
        Applique des variations imperceptibles pour éviter le fingerprinting.
        
        Variations appliquées:
        - Micro color shift (invisible à l'œil)
        - Subtle noise injection (grain)
        - Tiny speed variation (±0.1-0.3%)
        - Random crop (1-3 pixels selon intensité)
        
        Args:
            video_path: Vidéo source
            output_path: Chemin de sortie
            intensity: "subtle", "moderate", ou "aggressive"
            
        Returns:
            Chemin de la vidéo modifiée
        """
        self._log(f"   🔒 Anti-fingerprint ({intensity}): {video_path}")
        
        if intensity not in ANTI_FINGERPRINT_PARAMS:
            intensity = "subtle"
        
        p = ANTI_FINGERPRINT_PARAMS[intensity]
        
        color_shift = random.uniform(-p["color"], p["color"])
        noise_level = random.randint(1, p["noise"])
        speed_var = 1 + random.uniform(-p["speed"], p["speed"])
        crop_px = random.randint(0, p["crop"])
        
        self._log(f"      Color shift: {color_shift:+.4f}")
        self._log(f"      Noise level: {noise_level}")
        self._log(f"      Speed var: {speed_var:.4f}x")
        self._log(f"      Crop: {crop_px}px")
        
        filters = []
        
        if color_shift != 0:
            filters.append(f"colorbalance=rs={color_shift}:gs={color_shift}:bs={color_shift}")
        
        if noise_level > 0:
            filters.append(f"noise=alls={noise_level}:allf=t")
        
        if abs(speed_var - 1.0) > 0.0001:
            pts_factor = 1.0 / speed_var
            filters.append(f"setpts={pts_factor}*PTS")
        
        if crop_px > 0:
            filters.append(f"crop=iw-{crop_px*2}:ih-{crop_px*2}:{crop_px}:{crop_px}")
            filters.append("scale=iw+mod(iw\\,2):ih+mod(ih\\,2)")
        
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        if filters:
            filter_chain = ",".join(filters)
            
            cmd = [
                "ffmpeg", "-y",
                "-i", video_path,
                "-vf", filter_chain,
                "-c:v", "libx264",
                "-preset", "slow",
                "-crf", "18",
                "-pix_fmt", "yuv420p"
            ]
            
            if abs(speed_var - 1.0) > 0.0001:
                atempo = speed_var
                if 0.5 <= atempo <= 2.0:
                    cmd.extend(["-af", f"atempo={atempo}"])
                else:
                    cmd.extend(["-c:a", "copy"])
            else:
                cmd.extend(["-c:a", "copy"])
            
            cmd.append(output_path)
        else:
            cmd = [
                "ffmpeg", "-y",
                "-i", video_path,
                "-c", "copy",
                output_path
            ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            self._log(f"   ❌ Erreur: {result.stderr}")
            raise RuntimeError(f"FFmpeg anti-fingerprint failed: {result.stderr}")
        
        self._log(f"   ✓ Anti-fingerprint appliqué: {output_path}")
        
        return output_path
    
    def generate_unique_id(self) -> str:
        """Génère un ID unique pour cette session."""
        return str(uuid.uuid4())[:8]
    
    def get_variation_report(self, intensity: str = "subtle") -> Dict[str, Any]:
        """
        Génère un rapport des variations qui seront appliquées.
        
        Args:
            intensity: Niveau d'intensité
            
        Returns:
            Dict avec les paramètres de variation
        """
        p = ANTI_FINGERPRINT_PARAMS.get(intensity, ANTI_FINGERPRINT_PARAMS["subtle"])
        
        return {
            "intensity": intensity,
            "max_color_shift": p["color"],
            "max_noise_level": p["noise"],
            "max_speed_variation_percent": p["speed"] * 100,
            "max_crop_pixels": p["crop"],
            "unique_id": self.generate_unique_id()
        }


if __name__ == "__main__":
    print("=" * 60)
    print("📋 METADATA INJECTOR - Test Mode")
    print("=" * 60)
    
    injector = MetadataInjector(verbose=True)
    
    print(f"\n🔧 FFmpeg disponible: {injector.check_ffmpeg()}")
    
    print(f"\n📋 Paramètres anti-fingerprint:")
    for name, params in ANTI_FINGERPRINT_PARAMS.items():
        print(f"   {name}:")
        print(f"      Color: ±{params['color']}")
        print(f"      Noise: 1-{params['noise']}")
        print(f"      Speed: ±{params['speed']*100:.1f}%")
        print(f"      Crop: 0-{params['crop']}px")
    
    print(f"\n🔧 Test rapport de variation:")
    for intensity in ["subtle", "moderate", "aggressive"]:
        report = injector.get_variation_report(intensity)
        print(f"   {intensity}: ID={report['unique_id']}")
    
    print("\n✅ Module metadata_injector.py fonctionnel")
